### ISSUE TITLE
FeatureAttributes - Champs manquants dans le modèle

### ISSUE THREAD

**Issue by SimonSAMPERE** [isogeo/isogeo-api-py-minsdk#129]
*length*, *scale* et *precision* sont trois champs de description des attributs qui sont créés par le Scan FME mais n'apparaissent pas dans app.

Ces trois champs n'apparaissent pas dans la documentation de l'API et ne sont donc pas pris en compte dans la classe [**FeatureAttribute**](https://github.com/isogeo/isogeo-api-py-minsdk/blob/master/isogeo_pysdk/models/feature_attributes.py) du sdk Python.

L'erreur Python suivante a été signalée en utilisant le module [`duplicator`](https://github.com/isogeo/migrations-toolbelt/blob/master/isogeo_migrations_toolbelt/duplicate/duplicator.py) du [migration-toolbelt](https://github.com/isogeo/migrations-toolbelt/), pour dupliquer une fiche de métadonnées décrivant un jeu de données vecteurs dont certains des attributs étaient décris par les champs *length*, *scale* ou *precision*.

```
Traceback (most recent call last):
  File "c:/$USERNAME/Documents/GitHub/migrations-toolbelt/scripts/jura/duplicate_script_jura.py", line 178, in <module>
    copymark_title=False
  File "c:\$USERNAME\documents\github\migrations-toolbelt\isogeo_migrations_toolbelt\duplicate\duplicator.py", line 534, in duplicate_into_other_group
    metadata_source=self.metadata_source, metadata_dest=md_dst
  File "C:\$USERNAME\Documents\GitHub\migrations-toolbelt\.venv\lib\site-packages\isogeo_pysdk\api\routes_feature_attributes.py", line 379, in import_from_dataset
    attribute = FeatureAttribute(**attribute)
TypeError: __init__() got an unexpected keyword argument 'length'
```

Au moment d'importer les attributs de la fiche source dans la fiche de destination créée, une requête est effectuée sur les attributs de la couche source. Pour chacun des attributs renvoyés par l'API, la classe **FeatureAttribute** est instanciée. Lorsque l'objet attribut renvoyé par l'API est doté d'une clef autre que *_id*, *alias*, *dataType*, *description*, *language* ou *name* l'erreur ci-dessus est signalée lors de l'instanciation. 

**Ressources :**
* UUID d'une fiche d'exemple pour *length* : 6c4b948c72c248bc95964201da654176
* UUID d'une fiche d'exemple pour *scale* et *precision* : 0003fba1559945879f0205f8c652afa8
* fichier log associé : [migration_jura.log](https://github.com/isogeo/isogeo-api-py-minsdk/files/3808523/migration_jura.log)

**Comment by SimonSAMPERE** [comment]
exemple de code Python pour reproduire le bug : 
```Python
md_id=6c4b948c72c248bc95964201da654176
migrator = MetadataDuplicator(
            api_client=isogeo,
            source_metadata_uuid=md_id
        )
        migrator.duplicate_into_other_group(
            destination_workgroup_uuid=environ.get("ISOGEO_WORK_GROUP_MIGRATION"),
            copymark_abstract=True,
            copymark_title=True
        )
```
