### ISSUE TITLE
Faire deux recherches à la suite avec *whole_result=True* entraîne une erreur

### ISSUE THREAD

**Issue by SimonSAMPERE** [isogeo/isogeo-api-py-minsdk#160]
Exemple de code permettant d'obtenir l'erreur en question
```python
# Instanciation du client
isogeo = Isogeo(
    client_id=environ.get("ISOGEO_API_USER_LEGACY_CLIENT_ID"),
    client_secret=environ.get("ISOGEO_API_USER_LEGACY_CLIENT_SECRET"),
    auth_mode="user_legacy",
    auto_refresh_url="{}/oauth/token".format(environ.get("ISOGEO_ID_URL")),
    platform=environ.get("ISOGEO_PLATFORM", "qa"),
)
# Authentification
isogeo.connect(
    username=environ.get("ISOGEO_USER_NAME"),
    password=environ.get("ISOGEO_USER_PASSWORD"),
)
# Recherches
src_md = isogeo.search(
    group=environ.get("ISOGEO_ORIGIN_WORKGROUP"),
    query="catalog:{}".format(src_cat_uuid),
    whole_results=True
)

trg_md = isogeo.search(
    group=environ.get("ISOGEO_ORIGIN_WORKGROUP"),
    query="catalog:{}".format(trg_cat_uuid),
    whole_results=True
)
```

Erreur : 
```powershell
Traceback (most recent call last):
  File "c:/Users/SimonSAMPERE/Documents/GitHub/migrations-toolbelt/scripts/rouen/export_md.py", line 68, in <module>
    whole_results=True
  File "C:\Users\SimonSAMPERE\Documents\GitHub\migrations-toolbelt\.venv\lib\site-packages\isogeo_pysdk\decorators.py", line 56, in wrapper
    return decorated_func(*args, **kwargs)
    total_results=total_results, **search_params
  File "C:\Users\SimonSAMPERE\AppData\Local\Programs\Python\Python37-32\lib\asyncio\tasks.py", line 581, in ensure_future
    task = loop.create_task(coro_or_future)
  File "C:\Users\SimonSAMPERE\AppData\Local\Programs\Python\Python37-32\lib\asyncio\base_events.py", line 403, in create_task
    self._check_closed()
  File "C:\Users\SimonSAMPERE\AppData\Local\Programs\Python\Python37-32\lib\asyncio\base_events.py", line 480, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
sys:1: RuntimeWarning: coroutine 'ApiSearch.search_metadata_asynchronous' was never awaited
```

L'origine de cette erreur dans le code est indiquée au niveau de la deuxième requête. Exécuter le même code en passant l'argument `whole_results` des deux requêtes à False n'entraîne pas d'erreur. Cette erreur est manifestement liée à la composante asynchrone du module **ApiSearch** dont la méthode *search(...)* est une propriété. Cette erreur pourrait provenir du fait que cette méthode  s'appelle elle même lorsque `whole_results=True`.

**Comment by SimonSAMPERE** [comment]
This issue looks like [this one](https://github.com/isogeo/isogeo-api-py-minsdk/issues/147) which was fixed with [last release](https://github.com/isogeo/isogeo-api-py-minsdk/releases/tag/3.3.0). The solution is to update isogeo-pysdk version into [isogeo-migrations-toolbelt](https://github.com/isogeo/migrations-toolbelt).
